const members = [
  // 01
  { name: "Arlecchino", 
    quote: "Everyone calls me Daddy, you should be too", 
    photo: "assets/images/members/1.jpg", 
    social: "Daddy69", 
    fact: "Can be both you Mommy and Daddy", 
    ambition: "Alive", 
    message: "Dont do suicide", 
    extraPhotos: ["assets/images/members/01a.jpg", "assets/images/members/01b.jpg", "assets/images/members/01c.jpg"] },
  // 02
  { name: "Jill Valentine", 
    quote: "awawawawaaw", 
    photo: "assets/images/members/2.jpg", 
    social: "Not Your Valentine", 
    fact: "not born in valentine day", 
    ambition: "Marry leon", 
    message: "Fuck U", 
    extraPhotos: ["assets/images/members/02a.jpg", "assets/images/members/02b.jpg", "assets/images/members/02c.jpg"] },
  // 03
  { name: "", 
    quote: "", 
    photo: "assets/images/members/3.jpg", 
    social: "", 
    fact: "", 
    ambition: "", 
    message: "", 
    extraPhotos: ["assets/images/members/03a.jpg", "assets/images/members/03b.jpg", "assets/images/members/03c.jpg"] },
  // 04
  { name: "", 
    quote: "", 
    photo: "assets/images/members/4.jpg", 
    social: "", 
    fact: "", 
    ambition: "", 
    message: "", 
    extraPhotos: ["assets/images/members/04a.jpg", "assets/images/members/04b.jpg", "assets/images/members/04c.jpg"] },
  // 05
  { name: "", 
    quote: "", 
    photo: "assets/images/members/5.jpg", 
    social: "", 
    fact: "", 
    ambition: "", 
    message: "", 
    extraPhotos: ["assets/images/members/05a.jpg", "assets/images/members/05b.jpg", "assets/images/members/05c.jpg"] },
  // 06
  { name: "", 
    quote: "", 
    photo: "assets/images/members/6.jpg", 
    social: "", 
    fact: "", 
    ambition: "", 
    message: "", 
    extraPhotos: ["assets/images/members/06a.jpg", "assets/images/members/06b.jpg", "assets/images/members/06c.jpg"] },
  // 07
  { name: "", 
    quote: "", 
    photo: "assets/images/members/7.jpg", 
    social: "", 
    fact: "", 
    ambition: "", 
    message: "", 
    extraPhotos: ["assets/images/members/07a.jpg", "assets/images/members/07b.jpg", "assets/images/members/07c.jpg"] },
  // 08
  { name: "", 
    quote: "", 
    photo: "assets/images/members/8.jpg", 
    social: "", 
    fact: "", 
    ambition: "", 
    message: "", 
    extraPhotos: ["assets/images/members/08a.jpg", "assets/images/members/08b.jpg", "assets/images/members/08c.jpg"] },
  // 09
  { name: "", 
    quote: "", 
    photo: "assets/images/members/9.jpg", 
    social: "", 
    fact: "", 
    ambition: "", 
    message: "", 
    extraPhotos: ["assets/images/members/09a.jpg", "assets/images/members/09b.jpg", "assets/images/members/09c.jpg"] },
  // 10
  { name: "", 
    quote: "", 
    photo: "assets/images/members/10.jpg", 
    social: "", 
    fact: "", 
    ambition: "", 
    message: "", 
    extraPhotos: ["assets/images/members/10a.jpg", "assets/images/members/10b.jpg", "assets/images/members/10c.jpg"] },
  // 11
  { name: "", 
    quote: "", 
    photo: "assets/images/members/11.jpg", 
    social: "", 
    fact: "", 
    ambition: "", 
    message: "", 
    extraPhotos: ["assets/images/members/11a.jpg", "assets/images/members/11b.jpg", "assets/images/members/11c.jpg"] },
  // 12
  { name: "", 
    quote: "", 
    photo: "assets/images/members/12.jpg", 
    social: "", 
    fact: "", 
    ambition: "", 
    message: "", 
    extraPhotos: ["assets/images/members/12a.jpg", "assets/images/members/12b.jpg", "assets/images/members/12c.jpg"] },
  // 13
  { name: "", 
    quote: "", 
    photo: "assets/images/members/13.jpg", 
    social: "", 
    fact: "", 
    ambition: "", 
    message: "", 
    extraPhotos: ["assets/images/members/13a.jpg", "assets/images/members/13b.jpg", "assets/images/members/13c.jpg"] },
  // 14
  { name: "", 
    quote: "", 
    photo: "assets/images/members/14.jpg", 
    social: "", 
    fact: "", 
    ambition: "", 
    message: "", 
    extraPhotos: ["assets/images/members/14a.jpg", "assets/images/members/14b.jpg", "assets/images/members/14c.jpg"] },
  // 15
  { name: "", 
    quote: "", 
    photo: "assets/images/members/15.jpg", 
    social: "", 
    fact: "", 
    ambition: "", 
    message: "", 
    extraPhotos: ["assets/images/members/15a.jpg", "assets/images/members/15b.jpg", "assets/images/members/15c.jpg"] },
  // 16
  { name: "Ikhsan Sofyan", 
    quote: "Now will always be late. Dont wait for the right time and just do it", 
    photo: "assets/images/members/16.jpg", 
    social: "https://www.instagram.com/sann.mngr/", 
    handle: "Sann.mngr",
    fact: "i can eat 3 bowls of mie ayam", 
    ambition: "Work in Australia and be rich", 
    message: "Jangan Sampai Lupa sama Kawan Sendiri!", 
    extraPhotos: ["assets/images/members/16a.jpeg", "assets/images/members/16b.jpeg", "assets/images/members/16c.jpeg"] },
  // 17
  { name: "", 
    quote: "", 
    photo: "assets/images/members/17.jpg", 
    social: "", 
    fact: "", 
    ambition: "", 
    message: "", 
    extraPhotos: ["assets/images/members/17a.jpg", "assets/images/members/17b.jpg", "assets/images/members/17c.jpg"] },
  // 18
  { name: "", 
    quote: "", 
    photo: "assets/images/members/18.jpg", 
    social: "", 
    fact: "", 
    ambition: "", 
    message: "", 
    extraPhotos: ["assets/images/members/18a.jpg", "assets/images/members/18b.jpg", "assets/images/members/18c.jpg"] },
  // 19
  { name: "", 
    quote: "", 
    photo: "assets/images/members/19.jpg", 
    social: "", 
    fact: "", 
    ambition: "", 
    message: "", 
    extraPhotos: ["assets/images/members/19a.jpg", "assets/images/members/19b.jpg", "assets/images/members/19c.jpg"] },
  // 20
  { name: "", 
    quote: "", 
    photo: "assets/images/members/20.jpg", 
    social: "", 
    fact: "", 
    ambition: "", 
    message: "", 
    extraPhotos: ["assets/images/members/20a.jpg", "assets/images/members/20b.jpg", "assets/images/members/20c.jpg"] },
  // 21
  { name: "", 
    quote: "", 
    photo: "assets/images/members/21.jpg", 
    social: "", 
    fact: "", 
    ambition: "", 
    message: "", 
    extraPhotos: ["assets/images/members/21a.jpg", "assets/images/members/21b.jpg", "assets/images/members/21c.jpg"] },
  // 22
  { name: "", 
    quote: "", 
    photo: "assets/images/members/22.jpg", 
    social: "", 
    fact: "", 
    ambition: "", 
    message: "", 
    extraPhotos: ["assets/images/members/22a.jpg", "assets/images/members/22b.jpg", "assets/images/members/22c.jpg"] },
  // 23
  { name: "", 
    quote: "", 
    photo: "assets/images/members/23.jpg", 
    social: "", 
    fact: "", 
    ambition: "", 
    message: "", 
    extraPhotos: ["assets/images/members/23a.jpg", "assets/images/members/23b.jpg", "assets/images/members/23c.jpg"] },
  // 24
  { name: "", 
    quote: "", 
    photo: "assets/images/members/24.jpg", 
    social: "", 
    fact: "", 
    ambition: "", 
    message: "", 
    extraPhotos: ["assets/images/members/24a.jpg", "assets/images/members/24b.jpg", "assets/images/members/24c.jpg"] },
  // 25
  { name: "", 
    quote: "", 
    photo: "assets/images/members/25.jpg", 
    social: "", 
    fact: "", 
    ambition: "", 
    message: "", 
    extraPhotos: ["assets/images/members/25a.jpg", "assets/images/members/25b.jpg", "assets/images/members/25c.jpg"] },
  // 26
  { name: "", 
    quote: "", 
    photo: "assets/images/members/26.jpg", 
    social: "", 
    fact: "", 
    ambition: "", 
    message: "", 
    extraPhotos: ["assets/images/members/26a.jpg", "assets/images/members/26b.jpg", "assets/images/members/26c.jpg"] },
  // 27
  { name: "", 
    quote: "", 
    photo: "assets/images/members/27.jpg", 
    social: "", 
    fact: "", 
    ambition: "", 
    message: "", 
    extraPhotos: ["assets/images/members/27a.jpg", "assets/images/members/27b.jpg", "assets/images/members/27c.jpg"] },
  // 28
  { name: "", 
    quote: "", 
    photo: "assets/images/members/28.jpg", 
    social: "", 
    fact: "", 
    ambition: "", 
    message: "", 
    extraPhotos: ["assets/images/members/28a.jpg", "assets/images/members/28b.jpg", "assets/images/members/28c.jpg"] },
  // 29
  { name: "", 
    quote: "", 
    photo: "assets/images/members/29.jpg", 
    social: "", 
    fact: "", 
    ambition: "", 
    message: "", extraPhotos: ["assets/images/members/29a.jpg", "assets/images/members/29b.jpg", "assets/images/members/29c.jpg"] },
  // 30
  { name: "", 
    quote: "", 
    photo: "assets/images/members/30.jpg", 
    social: "", 
    fact: "", 
    ambition: "", 
    message: "", 
    extraPhotos: ["assets/images/members/30a.jpg", "assets/images/members/30b.jpg", "assets/images/members/30c.jpg"] },
  // 31
  { name: "", 
    quote: "", 
    photo: "assets/images/members/31.jpg", 
    social: "", 
    fact: "", 
    ambition: "", 
    message: "", 
    extraPhotos: ["assets/images/members/31a.jpg", "assets/images/members/31b.jpg", "assets/images/members/31c.jpg"] },
  // 32
  { name: "", 
    quote: "", 
    photo: "assets/images/members/32.jpg", 
    social: "", 
    fact: "", 
    ambition: "", 
    message: "", 
    extraPhotos: ["assets/images/members/32a.jpg", "assets/images/members/32b.jpg", "assets/images/members/32c.jpg"] },
  // 33
  { name: "", 
    quote: "", 
    photo: "assets/images/members/33.jpg", 
    social: "", 
    fact: "", 
    ambition: "", 
    message: "", 
    extraPhotos: ["assets/images/members/33a.jpg", "assets/images/members/33b.jpg", "assets/images/members/33c.jpg"] },
  // 34
  { name: "", 
    quote: "", 
    photo: "assets/images/members/34.jpg", 
    social: "", 
    fact: "", 
    ambition: "", 
    message: "", 
    extraPhotos: ["assets/images/members/34a.jpg", "assets/images/members/34b.jpg", "assets/images/members/34c.jpg"] },
  // 35
  { name: "", 
    quote: "", 
    photo: "assets/images/members/35.jpg", 
    social: "", 
    fact: "", 
    ambition: "", 
    message: "", 
    extraPhotos: ["assets/images/members/35a.jpg", "assets/images/members/35b.jpg", "assets/images/members/35c.jpg"] },
  // 36
  { name: "", 
    quote: "", 
    photo: "assets/images/members/36.jpg", 
    social: "", 
    fact: "", 
    ambition: "", 
    message: "", 
    extraPhotos: ["assets/images/members/36a.jpg", "assets/images/members/36b.jpg", "assets/images/members/36c.jpg"] },
];
